# permissions to do edit environments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: environment-editor-role
rules:
- apiGroups:
  - clusterops.mmlt.nl
  resources:
  - environments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusterops.mmlt.nl
  resources:
  - environments/status
  verbs:
  - get
  - patch
  - update
